---
title: "Cases"
author: "Jens Hesel"
date: "18 mar 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(knitr)
library(lubridate)
library(readr)
#library(Hmisc)
```

```{r}
vital_sign_sample %>%
  filter(encounterId ==53069837) -> casedata


```



Selects random patient to show
```{r}
vital_sign_sample %>%
  filter(encounterId==54043611) -> test
```

```{r}
test %>%
  distinct(time, rr, pr, mBP, spO2) -> test
```

```{r}

#Laver variablen der skal arbejds med numerisk - nødvendigt for at kunne regne og plotte den
#I dette tilfælde er det en variabel af typen character derfor as.character
test$pr <- as.numeric(as.character(test$pr))
test$rr <- as.numeric(as.character(test$rr))
test$spO2 <- as.numeric(as.character(test$spO2))



#Plotter rr ift tiden 
ggplot(data=test, aes(x=time, y=value, color=variable)) + 
  geom_line(aes(y=pr, col="PR")) +
  geom_line(aes(y=rr, col="RR")) +
  geom_line(aes(y=spO2, col="spO2"))
```

Case 1
- Mange m?linger
- Total tid 0-3
```{r}
#Isolerer patient
vital_sign_final %>%
  filter(hr == 53104884) -> case1

case1$rr <- as.numeric(as.character(case1$rr))

#Plotter rr ift tiden 
ggplot(aes(x=encounter_enc_id, y=rr), data=case1) + geom_line()
```

```{r}
class(case2$rr)
```


Case 2
- f? m?linger
- Total tid 0-3
```{r}
#Isolerer patient
vital_sign_sample %>%
  filter(encounterId == 53203607) -> case2

case2$pr <- as.numeric(as.character(case2$pr))

#Plotter rr ift tiden 
ggplot(aes(x=time, y=pr), data=case2) + geom_line()
```


Case 3
- hullede m?linger
- Total tid 0-3
```{r}
#Isolerer patient
vital_sign_sample %>%
  filter(hr == 53069837) -> case3

#Plotter rr ift tiden 
ggplot(aes(x=encounter_enc_id, y=rr), data=case3) + geom_line()
```